#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<time.h>

char inputChar()
{
	
	/*This function is called by testme() to provide an input character used to 
	evaluate the series of IF statements that set the program state.  It has 
	been implemented to 1) create an array of only the characters tested by 
	those IF statements, and 2) randomly return one character of this array.*/
	
	char c_array[] = {'[', '(', '{', ' ', 'a', 'x', '}', ')', ']'};  
		//Array of tested characters
		
	int c_length = sizeof(c_array);
		//Variable storing length of array, used to bound rand()
		
	int c_index = rand() % c_length;
		//Variable to store random number generated by rand()
		//Will be used as the index of the c_array[]
		
	return c_array[c_index];
		//Return the c_array() character at the random index
}

char *inputString()
{
	
	/*This function is called by testme() to provide an input string 
	evaluated by the final IF statement.   It has been implemented to 
	1) allocate memory to store the string to be generated, 2) create an array 
	of only the tested characters, and 3) use a FOR loop to build the string 
	character by character by randomly setting the array index*/
	
	char *s_string = malloc(6); 
		//Pointer to store the randomly selected characters
		//Use pointer per the predefined function return type
		//Allocate space for six characters since using a pointer
	
	char s_array[] = {'r', 'e', 's', 't', '\0'};  
		//Create array of tested characters
		
	int s_length = sizeof(s_array);
		//Variable storing length of array, used to bound rand()
	
	int s_size = sizeof(s_array);
		//Bound for FOR loop and rand()
		
	int i; //Initiate FOR loop driver here for non-C99 compatibility
	
	for (i = 0; i < s_size; i++) {
		//FOR loop to fill s_string
		
		int s_index = rand() % s_size;
			//Randomly selected index to choose character from s_array[]
		
		s_string[i] = s_array[s_index];
			//Build s_string by assigning characters
		
    }//End FOR
	
    return s_string;
}

void testme()
{
  int tcCount = 0;
  char *s;
  char c;
  int state = 0;
  while (1)
  {
    tcCount++;
    c = inputChar();
    s = inputString();
    printf("Iteration %d: c = %c, s = %s, state = %d\n", tcCount, c, s, state);

    if (c == '[' && state == 0) state = 1;
    if (c == '(' && state == 1) state = 2;
    if (c == '{' && state == 2) state = 3;
    if (c == ' '&& state == 3) state = 4;
    if (c == 'a' && state == 4) state = 5;
    if (c == 'x' && state == 5) state = 6;
    if (c == '}' && state == 6) state = 7;
    if (c == ')' && state == 7) state = 8;
    if (c == ']' && state == 8) state = 9;
    if (s[0] == 'r' && s[1] == 'e'
       && s[2] == 's' && s[3] == 'e'
       && s[4] == 't' && s[5] == '\0'
       && state == 9)
    {
      printf("error ");
      exit(200);
    }
  }
}


int main(int argc, char *argv[])
{
    srand(time(NULL));
    testme();
    return 0;
}
